fix: add qt4-bigsur patch
cartr/homebrew-qt4 pull request #77
Opened 2021-09-03 13:28 UTC by qkdreyer

- https://bugs.webkit.org/show_bug.cgi?id=50991
- https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX11.3.sdk/usr/include/c%2B%2B/v1/cstddef#L37

2021-09-03 14:38 UTC, qkdreyer commented
```
cartr/qt4/qt@4: stable 4.8.7 (bottled), HEAD
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@4/4.8.7_6 (2,971 files, 76.4MB)
  Poured from bottle on 2021-08-03 at 10:17:07
/usr/local/Cellar/qt@4/4.8.7_6.0 (3,730 files, 85.3MB) *
  Built from source on 2021-09-03 at 16:09:02
From: https://github.com/qkdreyer/homebrew-qt4/blob/HEAD/qt@4.rb
```

2021-09-12 21:09 UTC, cartr requested changes
Thanks for submitting this PR, and apologies for the delay! I don't have a Mac handy to test this but it looks pretty reasonable.

Would you be interested in becoming a maintainer on this repository?

2021-09-12 21:09 UTC, cartr commented on qt@4.rb
> +  revision 7
I'm not sure we need to bump the revision here. (Mostly I'm kinda lazy and don't want to rebuild all the bottles.)

2021-09-12 21:09 UTC, cartr commented on qt@4.rb
> +    url "https://raw.githubusercontent.com/qkdreyer/homebrew-qt4/98a906e1ad47106c65021150938de61138799ea8/patches/qt4-bigsur.patch"
Could you please update this to say `/cartr/` instead of `/qkdreyer/` so it points at the original repository and not your fork?

2021-09-20 07:08 UTC, qkdreyer commented
Hello :) Sorry for my delayed response, I was in holidays.
I've just pushed changes you've required.
About becoming a maintainer, I guess I'm willing to try 🙃

2021-09-23 15:52 UTC, merged

2021-09-23 15:53 UTC, cartr commented
Looks great, thank you for submitting this!